#!/bin/bash

echo "Loading..."
cd ~
mkdir .projectinfinity
echo 'export PATH="~/.projectinfinity:$PATH"' >> .bashrc
cd .projectinfinity
touch ProjectInfinity
echo "#!/bin/bash" >> ProjectInfinity
echo "cd ~/Проєкти/Project-Infinity" >> ProjectInfinity
echo "source python/bin/activate" >> ProjectInfinity
echo "while true" >> ProjectInfinity
echo "do" >> ProjectInfinity
echo "./game.sh" >> ProjectInfinity
echo "done" >> ProjectInfinity
chmod +x ProjectInfinity
source ~/.bashrc
echo "Done!"
